# Generated by Django 3.1.4 on 2020-12-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_generation', '0002_auto_20201218_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livenews',
            old_name='email',
            new_name='data',
        ),
    ]
